# Generated by Django 4.2.14 on 2024-10-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_car_photo_3_remove_car_car_photo_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('KTM', 'Kathmandu'), ('BTL', 'Butwal'), ('BHR', 'Bhaktapur'), ('LAL', 'Lalitpur'), ('NPL', 'Nepalgunj'), ('DHA', 'Dhangadhi'), ('KAL', 'Kalaiya'), ('BIR', 'Biratnagar'), ('MOR', 'Morang'), ('SYN', 'Syndhuli'), ('PAR', 'Parbat'), ('KAV', 'Kavre'), ('SOL', 'Solukhumbu'), ('JAS', 'Jasikhel'), ('PAL', 'Palpa'), ('NAW', 'Nawalpur'), ('MAK', 'Makwanpur'), ('BAG', 'Baglung'), ('GUL', 'Gulmi'), ('DOL', 'Dolakha'), ('JUM', 'Jumla'), ('BAJ', 'Bajhang'), ('DHA', 'Dharan'), ('ROL', 'Rolpa'), ('RUK', 'Rukum'), ('SIND', 'Sindhupalchok'), ('KASK', 'Kaski'), ('SIRA', 'Siraha'), ('MGT', 'Magway'), ('BARA', 'Bara'), ('LAM', 'Lamjung'), ('SUR', 'Surkhet'), ('DOL', 'Dolang'), ('MUG', 'Muglin'), ('JAR', 'Jara'), ('BAIT', 'Baitadi'), ('SIND', 'Sindhuli'), ('KHOT', 'Khotang'), ('UDAY', 'Udayapur'), ('JHAPA', 'Jhapa'), ('NKT', 'Nuwakot'), ('TAN', 'Tanahun'), ('RAME', 'Ramechhap'), ('LAM', 'Lamjung'), ('MOR', 'Morang'), ('PRA', 'Pratapgarh'), ('RUP', 'Rupandehi'), ('NAW', 'Nawalpur'), ('DHA', 'Dharan'), ('DAI', 'Dailekh'), ('DOL', 'Dolakha'), ('SUN', 'Sunsari'), ('TAL', 'Talakjung'), ('MAHA', 'Mahottari'), ('SIRA', 'Siraha'), ('SIND', 'Sindhuli'), ('MUG', 'Mugu'), ('KANCH', 'Kanchanpur'), ('JHAPA', 'Jhapa'), ('KAV', 'Kavre'), ('DOL', 'Dolpa'), ('KARN', 'Karnali'), ('BAJ', 'Bajura'), ('RAUT', 'Rautahat'), ('DAN', 'Dang'), ('BANK', 'Banke')], max_length=100),
        ),
    ]
